@startuml

skinparam DefaultFontName "Noto Sans"
skinparam Dpi 144

entity "users" {
*id : bigint **<<PK>>**
--
*email: text
*password: text
*anonymous_id: text
*created_at: timestamp
*updated_at: timestamp
--
}

entity "user_roles" {
*id : bigint **<<PK>>**
--
*role: text
*created_at: timestamp
*updated_at: timestamp
--
*user_id: bigint **<<FK>>**
}

entity "files" {
*id : bigint **<<PK>>**
--
*original_file_name: text
*url: text
*media_type: text
*storage_type: text
*created_at: timestamp
*updated_at: timestamp
--
}

@enduml
