version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306" # localhost:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/db/init-test.sql:/docker-entrypoint-initdb.d/:ro
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    restart: always
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - db
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80

volumes:
  mysql-data:
